package com.tisp.accounts.entity;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
@MappedSuperclass
//Entities can then extend this BaseEntity class and inherit these properties
@Getter
//Generates getter methods for all fields in the class.
@Setter
//Generates setter methods for all non-final fields in the class.
@ToString
//Generates a toString() method for your class
public class BaseEntity {
    @Column(updatable = false)
    //means that the column will not be included in SQL UPDATE statements generated by the persistence provider
    private LocalDateTime createdAt;
    @Column(updatable = false)
    private String createdBy;
    @Column(insertable = false)
    //means that the column will not be included in SQL INSERT statements generated by the persistence provide
    private LocalDateTime updatedAt;
    @Column(insertable = false)
    private String updatedBy;

}
